import { fireEvent, render, screen } from '@testing-library/react';
import { describe, expect, it, vi } from 'vitest';
import { Field } from '../field.js';
import { ColorPicker } from './color-picker.js';
describe('ColorPicker', () => {
  it('opens a labelled 2D semantic grid and selects with keyboard', () => { const change = vi.fn(); render(<ColorPicker label="Accent tone" onValueChange={change} />); fireEvent.click(screen.getByRole('button', { name: 'Accent tone' })); const grid = screen.getByRole('grid', { name: 'Accent tone options' }); expect(grid).toBeInTheDocument(); expect(screen.getAllByRole('row')).toHaveLength(2); expect(screen.getByRole('gridcell', { name: 'Brand' })).toHaveAttribute('aria-selected', 'true'); fireEvent.keyDown(grid, { key: 'ArrowRight' }); fireEvent.keyDown(screen.getByRole('gridcell', { name: 'Success' }), { key: 'Enter' }); expect(change).toHaveBeenCalledWith('success'); expect(screen.queryByRole('grid')).toBeNull(); });
  it('keeps controlled values and reports controlled dismissal', () => { const change = vi.fn(); const close = vi.fn(); render(<ColorPicker label="Tone" value="danger" open onOpenChange={close} onValueChange={change} />); fireEvent.click(screen.getByRole('gridcell', { name: 'Brand' })); expect(change).toHaveBeenCalledWith('brand'); expect(close).toHaveBeenCalledWith(false); expect(screen.getByRole('button', { name: 'Tone' })).toHaveTextContent('Danger'); });
  it('rejects ambiguous, empty, disabled-only, and unavailable values', () => { expect(() => render(<ColorPicker label="Bad" options={[{ tone: 'brand', label: 'Brand' }, { tone: 'brand', label: 'Again' }]} />)).toThrow('must be unique'); expect(() => render(<ColorPicker label="Bad" options={[]} />)).toThrow('must not be empty'); expect(() => render(<ColorPicker label="Bad" options={[{ tone: 'brand', label: 'Brand', disabled: true }]} />)).toThrow('enabled tone'); expect(() => render(<ColorPicker label="Bad" defaultValue="danger" options={[{ tone: 'brand', label: 'Brand' }]} />)).toThrow('must match'); });
  it('wires Field, hidden form value, disabled state, and Skeleton', () => { render(<><Field label="Tone" hint="Choose one" required><ColorPicker label="Tone" name="tone" defaultValue="info" disabled /></Field><ColorPicker.Skeleton /></>); const trigger = screen.getByRole('button', { name: 'Tone' }); expect(trigger).toBeDisabled(); expect(trigger).toHaveAttribute('aria-required', 'true'); expect(trigger.getAttribute('aria-describedby')).toContain('hint'); expect(document.querySelector('input[type="hidden"]')).toHaveValue('info'); expect(document.querySelector('.cb-color-picker--skeleton')).toHaveAttribute('aria-hidden', 'true'); });
  it('closes an open palette when the control becomes disabled', () => { const close = vi.fn(); const { rerender } = render(<ColorPicker label="Tone" defaultOpen onOpenChange={close} />); expect(screen.getByRole('grid', { name: 'Tone options' })).toBeInTheDocument(); rerender(<ColorPicker label="Tone" defaultOpen disabled onOpenChange={close} />); expect(screen.queryByRole('grid', { name: 'Tone options' })).not.toBeInTheDocument(); expect(close).toHaveBeenLastCalledWith(false); });
});
