// Generated by ui-manifest.mjs during predev/prebuild. Do not edit.
import type { UiManifest } from './ui-manifest';

export const UI_MANIFEST: UiManifest = {
  "name": "@ceebee/ui",
  "version": "1.4.2",
  "skins": [
    "astra",
    "clarity",
    "moodboard"
  ],
  "exports": {
    "server": 15,
    "client": 25
  }
};
