// Generated by ui-manifest.mjs during predev/prebuild. Do not edit.
import type { UiManifest } from './ui-manifest';

export const UI_MANIFEST: UiManifest = {
  "name": "@ceebee/ui",
  "version": "0.4.1",
  "skins": [
    "astra",
    "clarity"
  ],
  "exports": {
    "server": 28,
    "client": 74
  }
};
